-- Deprecated: ElectroCompare has migrated its application data to MongoDB + Express.
-- Do not apply the permissive policies from older versions of this file.
-- Configure the backend using server/.env and run `npm run seed` from the server folder.
-- Authentication, products, orders, and price alerts are managed by the Express API.
